name: Publish PowerShell Module
description: Publishes a PowerShell module to the PowerShell Gallery.
inputs:
  NuGetApiKey:
    description: The NuGet API Key for PowerShell Gallery, with permission to push this module.
    required: true
  NugetRepository:
    description: Nuget Repository for push
    required: false
    default: PSGallery
  modulePath:
    description: The filesystem path to the module to publish.  If not provided, all directories that contains a .psd1 are published.
    required: false
  moduleFullpath:
    description: Fullpath for module (required for AutoVersion)
    required: false
  AutoVersion:
    type: choice
    description: Automatically versioning of Powershell Modules (require new commit after Workflow, to save Fingerprint of Module)
    default: false
    options: 
      - true
      - false
    required: false
  ChangedFiles:
    description: All changed files (by last commit) to process from (needed if you use multiple Modules with this Action) https://github.com/tj-actions/changed-files
    required: false
  ChangedFilesIgnoredExtensions:
    description: File extensions that should be ignored by ChangedFiles
    required: false

outputs:
  successfullyPublished: # id of output
    description: Whether or not the publish command was successful
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.NuGetApiKey }}
    - ${{ inputs.modulePath }}
    - ${{ inputs.NugetRepository }}
    - ${{ inputs.ChangedFiles }}
    - ${{ inputs.ChangedFilesIgnoredExtensions }}
