name: Publish PowerShell Module
description: Publishes a PowerShell module to the PowerShell Gallery.
inputs:
  NuGetApiKey:
    description: The NuGet API Key for PowerShell Gallery, with permission to push this module.
    required: true
  NugetRepository:
    description: Nuget Repository for push
    required: false
    default: PSGallery
  NugetRepositorySourceUrl:
      description: Nuget repository source url (for selfhosted nuget)
      required: false
  NugetRepositoryPublishUrl:
      description: Nuget repository publish url (for selfhosted nuget)
      required: false
  AutoVersion:
    type: choice
    description: Automatically versioning of Powershell Modules (require new commit after Workflow, to save Fingerprint of Module)
    default: false
    options: 
      - true
      - false
    required: false
  #Single modul build
  moduleName:
    description: The filesystem path to the module to publish.
    required: false
  modulePath:
    description: The filesystem path to the module to publish.
    required: false
  #Multiple modules build (with changed files)
  ChangedFiles:
    description: All changed files (by last commit) to process from (needed if you use multiple Modules with this Action) https://github.com/tj-actions/changed-files
    required: false
  ChangedFilesIgnoredExtensions:
    description: File extensions that should be ignored by ChangedFiles
    required: false
runs:
  using: docker
  image: Dockerfile